FROM node:22-alpine
WORKDIR /app
RUN corepack enable
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./turbo.json ./turbo.json
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./apps/frontend/package.json ./apps/frontend/package.json
COPY ./apps/frontend/package-lock.json ./apps/frontend/package-lock.json
RUN pnpm install
COPY ./apps/frontend ./apps/frontend
EXPOSE 5173
CMD ["pnpm","run","start:frontend"]

