FROM node:22-alpine
WORKDIR /app
RUN corepack enable
RUN corepack prepare pnpm@latest --activate
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./turbo.json ./turbo.json
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./apps/http_backend/package.json ./apps/http_backend/package.json
COPY ./packages/**/package.json  ./packages/**/package.json
COPY ./packages/db/dbcore/package.json ./packages/db/dbcore/package.json
COPY ./packages/db/db-timescale/package.json ./packages/db/db-timescale/package.json
RUN pnpm install
COPY ./packages ./packages
COPY ./apps/http_backend ./apps/http_backend
RUN cd apps/http_backend && npx tsc -b && cd ../..
RUN pnpm run dev:dbCore-generate && pnpm run dev:db-timescale-generate
EXPOSE 3000
CMD ["pnpm","run","start:http"]

